import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {runOpeningNotifications,openingKey} from '../scripts/opening-engine.mjs';
const now=Date.parse('2026-10-07T10:00:00+06:30'),DAY=86400000;
function fixture(){const db=new DatabaseSync(':memory:');const folder=new URL('../db/migrations/',import.meta.url);for(const f of readdirSync(folder).filter(n=>n.endsWith('.sql')).sort())db.exec(readFileSync(new URL(f,folder),'utf8'));db.exec('PRAGMA foreign_keys=ON');db.prepare('INSERT INTO users VALUES(?,?,?,?,1,?)').run('u','owner@example.test','User','hash',now);db.prepare('INSERT INTO profiles(user_id,display_name,language,updated_at,opening_notifications) VALUES(?,?,?,?,1)').run('u','User','my',now);return db;}
function event(db,id='g',status='pending'){db.prepare('INSERT INTO gifts(id,owner_id,token,content,template,plan,status,expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,'u','private-token-'+id,'{}','bloom','basic','test',now+DAY,now,now);db.prepare('INSERT INTO gift_openings(gift_id,opened_at,email_status) VALUES(?,?,?)').run(id,now,status);}
const options={now,clock:()=>now,origin:'https://gifts.example.test',from:'OurStory <accounts@example.test>'};
test('dry-run counts eligible events without mutating delivery state',async()=>{const db=fixture();try{event(db);const result=await runOpeningNotifications(db,{...options,dryRun:true});assert.equal(result.due,1);assert.equal(db.prepare('SELECT payload,attempts FROM gift_openings').get().payload,null);assert.equal(db.prepare('SELECT attempts FROM gift_openings').get().attempts,0);}finally{db.close();}});
test('one provider send per gift despite repeated jobs and hosting renewal',async()=>{const db=fixture();let calls=0;try{event(db);const send=async(p,key)=>{calls++;assert.ok(p.text.includes('/dashboard'));assert.ok(p.text.includes('မြန်မာ')||p.text.includes('Myanmar'));assert.equal(p.text.includes('private-token'),false);assert.equal(key,openingKey('g',now));return {id:'provider-id'};};await runOpeningNotifications(db,{...options,send});db.exec('UPDATE gifts SET expires_at=expires_at+86400000,revision=revision+1');await runOpeningNotifications(db,{...options,send});assert.equal(calls,1);assert.equal(db.prepare('SELECT email_status FROM gift_openings').get().email_status,'sent');}finally{db.close();}});
test('emails require current consent, verified account and available gift',async()=>{for(const sql of ['UPDATE profiles SET opening_notifications=0','UPDATE users SET verified=0',"UPDATE gifts SET status='draft'",`UPDATE gifts SET expires_at=${now-1}`,`UPDATE gifts SET reveal_at=${now+60000}`]){const db=fixture();try{event(db);db.exec(sql);let calls=0;await runOpeningNotifications(db,{...options,send:async()=>{calls++;return {id:'unexpected'};}});assert.equal(calls,0);assert.equal(db.prepare('SELECT email_status FROM gift_openings').get().email_status,'cancelled');}finally{db.close();}}});
test('opting in later never sends retroactive notices',async()=>{const db=fixture();try{event(db,'g','disabled');await runOpeningNotifications(db,{...options,send:async()=>{throw Error('must not send');}});assert.equal(db.prepare('SELECT email_status FROM gift_openings').get().email_status,'disabled');}finally{db.close();}});
test('ambiguous provider retry uses identical payload/key after five-minute backoff',async()=>{const db=fixture(),requests=[];try{event(db);const send=async(p,k)=>{requests.push([p,k]);if(requests.length===1)throw Error('response lost after accepted');return {id:'original-email'};};await runOpeningNotifications(db,{...options,send});await runOpeningNotifications(db,{...options,send});assert.equal(requests.length,1);db.exec("UPDATE profiles SET language='en'");const later=now+6*60000;await runOpeningNotifications(db,{...options,now:later,clock:()=>later,send});assert.equal(requests.length,2);assert.deepEqual(requests[0],requests[1]);}finally{db.close();}});
test('uncertain sends are held for review before provider key expires',async()=>{const db=fixture();let calls=0;try{event(db);const send=async()=>{calls++;throw Error('network timeout');};await runOpeningNotifications(db,{...options,send});const later=now+23*3600000;const result=await runOpeningNotifications(db,{...options,now:later,clock:()=>later,send});assert.equal(calls,1);assert.equal(result.review,1);assert.equal(db.prepare('SELECT email_status FROM gift_openings').get().email_status,'review');}finally{db.close();}});
test('five failed attempts stop automatic retries',async()=>{const db=fixture();let calls=0;try{event(db);const send=async()=>{calls++;throw Error('fail');};for(let n=0;n<6;n++){const later=now+n*6*60000;await runOpeningNotifications(db,{...options,now:later,clock:()=>later,send});}assert.equal(calls,5);assert.equal(db.prepare('SELECT email_status FROM gift_openings').get().email_status,'review');}finally{db.close();}});
test('worker lease excludes overlapping workers',async()=>{const db=fixture();try{event(db);db.prepare('INSERT INTO job_leases VALUES(?,?,?)').run('opening','other',now+60000);const result=await runOpeningNotifications(db,{...options,send:async()=>{throw Error('must not send');}});assert.equal(result.locked,true);assert.equal(db.prepare('SELECT attempts FROM gift_openings').get().attempts,0);}finally{db.close();}});
test('opt-out during a batch cancels subsequent messages',async()=>{const db=fixture();let calls=0;try{event(db,'a');event(db,'b');await runOpeningNotifications(db,{...options,send:async()=>{calls++;db.exec('UPDATE profiles SET opening_notifications=0');return {id:'first'};}});assert.equal(calls,1);assert.equal(db.prepare("SELECT email_status FROM gift_openings WHERE gift_id='b'").get().email_status,'cancelled');}finally{db.close();}});
test('read state is independent of email delivery and gift deletion cascades',async()=>{const db=fixture();try{event(db);db.prepare('UPDATE gift_openings SET read_at=?').run(now);await runOpeningNotifications(db,{...options,send:async()=>({id:'email'})});assert.equal(db.prepare('SELECT read_at FROM gift_openings').get().read_at,now);db.exec("DELETE FROM gifts WHERE id='g'");assert.equal(db.prepare('SELECT COUNT(*) n FROM gift_openings').get().n,0);}finally{db.close();}});
test('English notices contain authenticated links and distinct per-event keys',async()=>{const db=fixture();try{event(db);db.exec("UPDATE profiles SET language='en'");await runOpeningNotifications(db,{...options,send:async(p)=>{assert.equal(p.subject,'Your OurStory gift was opened');assert.ok(p.text.includes('does not verify'));assert.ok(!p.text.includes('/gift/'));return {id:'email'};}});assert.notEqual(openingKey('g',now),openingKey('another-gift',now));assert.notEqual(openingKey('g',now),openingKey('g',now+1));}finally{db.close();}});
test('non-HTTPS production origins and missing delivery config are rejected',async()=>{const db=fixture();try{event(db);await assert.rejects(runOpeningNotifications(db,{...options,origin:'http://public.example',dryRun:true}),/HTTPS/);await assert.rejects(runOpeningNotifications(db,{...options}),/configured/);}finally{db.close();}});
test('migration preserves existing gifts and opts old accounts out by default',()=>{const db=new DatabaseSync(':memory:');try{const folder=new URL('../db/migrations/',import.meta.url);for(const f of readdirSync(folder).filter(n=>n.endsWith('.sql')&&!n.startsWith('0009')).sort())db.exec(readFileSync(new URL(f,folder),'utf8'));db.prepare('INSERT INTO users VALUES(?,?,?,?,1,?)').run('u','owner@example.test','User','hash',now);db.prepare('INSERT INTO profiles(user_id,display_name,language,updated_at,renewal_reminders) VALUES(?,?,?,?,1)').run('u','User','my',now);db.prepare('INSERT INTO gifts(id,owner_id,token,content,template,plan,status,expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run('old','u','old-private-token','{}','film','basic','published',now+DAY,now,now);db.exec(readFileSync(new URL('0009_gift_openings.sql',folder),'utf8'));assert.equal(db.prepare('SELECT opening_notifications FROM profiles').get().opening_notifications,0);assert.equal(db.prepare('SELECT renewal_reminders FROM profiles').get().renewal_reminders,1);assert.equal(db.prepare('SELECT status,template FROM gifts').get().template,'film');assert.equal(db.prepare('SELECT COUNT(*) n FROM gift_openings').get().n,0);}finally{db.close();}});
