import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {runReminders,reminderWindow,reminderKey} from '../scripts/reminder-engine.mjs';
const now=Date.parse('2026-10-07T08:00:00+06:30'),DAY=86400000;
function fixture(){const db=new DatabaseSync(':memory:');const folder=new URL('../db/migrations/',import.meta.url);for(const f of readdirSync(folder).filter(n=>n.endsWith('.sql')).sort())db.exec(readFileSync(new URL(f,folder),'utf8'));db.exec('PRAGMA foreign_keys=ON;');db.prepare('INSERT INTO users VALUES(?,?,?,?,1,?)').run('u','test@example.test','User','hash',now);db.prepare('INSERT INTO profiles(user_id,display_name,language,updated_at,renewal_reminders) VALUES(?,?,?,?,1)').run('u','User','my',now);return db;}
function gift(db,id,left=3*DAY,status='published',paid='order'){db.prepare('INSERT INTO gifts(id,owner_id,token,content,template,plan,status,paid_order_id,expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,'u','token-'+id,'{}','bloom','basic',status,paid,now+left,now,now);}
const options={now,clock:()=>now,origin:'https://gifts.example.test',from:'OurStory <accounts@example.test>'};
test('reminder windows choose one threshold without sending expired or early notices',()=>{assert.equal(reminderWindow(now,now),null);assert.equal(reminderWindow(now+DAY,now),1);assert.equal(reminderWindow(now+DAY+1,now),7);assert.equal(reminderWindow(now+7*DAY,now),7);assert.equal(reminderWindow(now+7*DAY+1,now),null);});
test('dry-run skips nonpaid/test/draft/expired gifts and makes no delivery records',async()=>{const db=fixture();try{gift(db,'paid');gift(db,'test',2*DAY,'test');gift(db,'draft',2*DAY,'draft');gift(db,'free',2*DAY,'published',null);gift(db,'expired',-1);gift(db,'early',8*DAY);assert.equal((await runReminders(db,{...options,dryRun:true})).due,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM reminder_deliveries').get().n,0);}finally{db.close();}});
test('consent and verified email are required',async()=>{const db=fixture();try{gift(db,'g');db.exec('UPDATE profiles SET renewal_reminders=0');assert.equal((await runReminders(db,{...options,dryRun:true})).due,0);db.exec('UPDATE profiles SET renewal_reminders=1;UPDATE users SET verified=0;');assert.equal((await runReminders(db,{...options,dryRun:true})).due,0);}finally{db.close();}});
test('sent notices are not repeated and renewed expiry produces a new key',async()=>{const db=fixture();let calls=0;try{gift(db,'g');const send=async(payload,key)=>{calls++;assert.ok(payload.text.includes('/edit/g?step=3'));assert.equal(payload.text.includes('token-g'),false);assert.ok(payload.text.includes('သက်တမ်း'));return {id:'email-'+calls};};await runReminders(db,{...options,send});await runReminders(db,{...options,send});assert.equal(calls,1);db.prepare('UPDATE gifts SET expires_at=?').run(now+5*DAY);await runReminders(db,{...options,send});assert.equal(calls,2);assert.notEqual(reminderKey('g',now+3*DAY,7),reminderKey('g',now+5*DAY,7));}finally{db.close();}});
test('provider failure retries the identical payload/key after backoff',async()=>{const db=fixture();const requests=[];try{gift(db,'g');const send=async(payload,key)=>{requests.push([payload,key]);if(requests.length===1)throw Error('timeout after accepted');return {id:'same-provider-id'};};await runReminders(db,{...options,send});await runReminders(db,{...options,send});assert.equal(requests.length,1);const later=now+16*60000;await runReminders(db,{...options,now:later,clock:()=>later,send});assert.deepEqual(requests[0],requests[1]);assert.equal(db.prepare('SELECT status FROM reminder_deliveries').get().status,'sent');}finally{db.close();}});
test('ambiguous send is held for review beyond the provider retry window',async()=>{const db=fixture();let calls=0;try{gift(db,'g');const send=async()=>{calls++;throw Error('timeout');};await runReminders(db,{...options,send});const later=now+23*3600000;const r=await runReminders(db,{...options,now:later,clock:()=>later,send});assert.equal(calls,1);assert.equal(r.review,1);assert.equal(db.prepare('SELECT status FROM reminder_deliveries').get().status,'review');}finally{db.close();}});
test('overlapping worker is excluded by a lease',async()=>{const db=fixture();try{gift(db,'g');db.prepare('INSERT INTO job_leases VALUES(?,?,?)').run('renewal','other',now+60000);const r=await runReminders(db,{...options,send:async()=>{throw Error('must not send');}});assert.equal(r.locked,true);assert.equal(db.prepare('SELECT COUNT(*) n FROM reminder_deliveries').get().n,0);}finally{db.close();}});
test('pending reminder cancels when consent is withdrawn or expiry changes',async()=>{for(const change of ['UPDATE profiles SET renewal_reminders=0','UPDATE gifts SET expires_at=expires_at+86400000']){const db=fixture();try{gift(db,'g');await runReminders(db,{...options,send:async()=>{throw Error('timeout');}});db.exec(change);await runReminders(db,{...options,send:async()=>({id:'new'})});assert.equal(db.prepare("SELECT status FROM reminder_deliveries ORDER BY expires_at LIMIT 1").get().status,'cancelled');}finally{db.close();}}});
test('recipient opted out during a batch is rechecked before the next email',async()=>{const db=fixture();let calls=0;try{gift(db,'a');gift(db,'b');await runReminders(db,{...options,send:async()=>{calls++;db.exec('UPDATE profiles SET renewal_reminders=0');return {id:'email'};}});assert.equal(calls,1);}finally{db.close();}});
test('7-day and 1-day notices each send once for the same hosting period',async()=>{const db=fixture();let calls=0;try{gift(db,'g');const send=async()=>({id:'email-'+(++calls)});await runReminders(db,{...options,send});const later=now+2.5*DAY;await runReminders(db,{...options,now:later,clock:()=>later,send});await runReminders(db,{...options,now:later,clock:()=>later,send});assert.equal(calls,2);assert.deepEqual(db.prepare('SELECT days FROM reminder_deliveries ORDER BY days').all().map(row=>row.days),[1,7]);}finally{db.close();}});
