import {useEffect,useState} from 'react';
import {ArrowUpRight,Sparkles,RotateCcw} from 'lucide-react';
import {defaultBox,giftStyles,type BoxConfig} from '@/lib/box';
import {Gift3D} from './gift-3d';
import {GiftStyleOptions} from './gift-options';
export function GiftCollection({my=false}:{my?:boolean}){
 const [box,setBox]=useState<BoxConfig>({...defaultBox,style:'bouquet',effect:'petals'}),[opening,setOpening]=useState(false),lang=my?'my':'en';
 useEffect(()=>{if(!opening)return;const timer=setTimeout(()=>setOpening(false),2600);return()=>clearTimeout(timer);},[opening]);
 const style=giftStyles.find(item=>item.id===box.style)!;
 return <section id="gift-collection" className="gift-collection section-wrap" lang={lang}><div className="collection-heading"><span className="eyebrow"><Sparkles size={15}/>{my?'လက်ဆောင်ထဲမှာ အချစ်တွေထည့်မယ်':'A LITTLE MAGIC, BEFORE THE MEMORIES'}</span><h2>{my?<>ချစ်ရသူအတွက်<br/><em>ဘယ်လက်ဆောင်လေး ရွေးမလဲ။</em></>:<>Say it with flowers.<br/><em>Or a little bear hug.</em></>}</h2><p>{my?'လက်ဆောင် ၄ မျိုး၊ ခံစားချက်တစ်ခု။ ကိုယ်ပိုင်အရောင်နဲ့ အမှတ်တရလေးတွေကို ထည့်ပြီး ပေးပါ။':'Four thoughtful gifts. One beautiful story. Choose a surprise that feels like them.'}</p></div><div className="collection-studio"><div className="collection-preview"><div className="collection-preview-top"><span>OURSTORY ATELIER</span><span>{my?'စိတ်ကြိုက်လက်ဆောင်':'YOUR PERSONAL TOUCH'}</span></div><Gift3D box={{...box,initials:'H & M'}} opening={opening} lang={lang}/><div className="collection-preview-bottom"><div><small>{my?'လက်ဆောင် collection':'THE GIFT COLLECTION'}</small><h3>{my?style.my:style.name}</h3></div><button type="button" className="collection-replay" aria-label={my?'Animation စမ်းမယ်':'Preview gift animation'} disabled={opening} onClick={()=>setOpening(true)}><RotateCcw size={18}/>{my?'စမ်းမယ်':'Try the magic'}</button></div></div><div className="collection-choices"><GiftStyleOptions box={box} onChange={next=>{setOpening(false);setBox({...next,effect:next.style==='bouquet'?'petals':'hearts'});}} lang={lang}/><div className="collection-note"><Sparkles size={20}/><p>{my?'လက်ဆောင်ပုံစံအားလုံးကို Basic နဲ့ Premium မှာ ရွေးနိုင်ပါတယ်။ ဒါတွေက digital gifts ပါ။':'Every gift style is included in Basic and Premium. These are digital keepsakes.'}</p></div><a className="btn primary" href={'/create?gift='+box.style}>{my?'ဒီလက်ဆောင် ဖန်တီးမယ်':'Make this their gift'}<ArrowUpRight size={18}/></a></div></div></section>;
}
