import {Canvas,useThree} from '@react-three/fiber';
import {OrbitControls,RoundedBox} from '@react-three/drei';
import {useEffect} from 'react';
import {ShopItemModel} from './gift-shop-model';
import {boxColors,ribbonColors,type BoxConfig} from '@/lib/box';
import {shopKinds,shopSlots,type ShopKind,type ShopSlot} from '@/lib/gift-shop';
function Guard({onFailure}:{onFailure:()=>void}){const {gl}=useThree();useEffect(()=>{const lost=(e:Event)=>{e.preventDefault();onFailure();};gl.domElement.addEventListener('webglcontextlost',lost);return()=>gl.domElement.removeEventListener('webglcontextlost',lost);},[gl,onFailure]);return null;}
function Room({box,selected,onPick,onPlace}:{box:BoxConfig;selected:ShopKind|null;onPick:(kind:ShopKind)=>void;onPlace:(slot:ShopSlot)=>void}){
 const c=boxColors[box.color],r=ribbonColors[box.ribbon].color;
 return <><mesh position={[0,.6,-1.7]}><boxGeometry args={[6.3,3.7,.15]}/><meshStandardMaterial color="#f0e6d6"/></mesh><mesh position={[0,-1.2,0]}><boxGeometry args={[6.4,.15,4.7]}/><meshStandardMaterial color="#d7bea2"/></mesh>{[-1,1].map(side=><mesh key={side} position={[side*3.1,.6,-.5]}><boxGeometry args={[.12,3.7,2.5]}/><meshStandardMaterial color="#e4d6c3"/></mesh>)}
  {shopKinds.map((kind,i)=><group key={kind} position={[(i-1)*1.75,.4,-.83]} onClick={e=>{e.stopPropagation();onPick(kind);}}><mesh position={[0,.55,-.72]}><torusGeometry args={[.68,.045,8,32,Math.PI]}/><meshStandardMaterial color="#b78c62"/></mesh>{[-1,1].map(side=><mesh key={side} position={[side*.68,.08,-.72]}><cylinderGeometry args={[.045,.045,.9,8]}/><meshStandardMaterial color="#b78c62"/></mesh>)}<mesh position={[0,-.42,0]}><boxGeometry args={[1.52,.14,1.15]}/><meshStandardMaterial color="#ae7d56"/></mesh><mesh position={[0,-.30,0]}><cylinderGeometry args={[.57,.57,.1,24]}/><meshStandardMaterial color={selected===kind?'#9fae8b':'#eedbc5'}/></mesh><group position={[0,.02,0]} scale={.48}><ShopItemModel kind={kind} box={box}/></group></group>)}
  <group position={[0,1.63,-1.50]}><RoundedBox args={[2.15,.37,.10]} radius={.08} smoothness={2}><meshStandardMaterial color="#597157"/></RoundedBox>{[-1,0,1].map(i=><mesh key={i} position={[i*.4,0,.08]} rotation={[0,0,Math.PI/4]}><boxGeometry args={[.10,.10,.025]}/><meshStandardMaterial color="#f5dbc0"/></mesh>)}</group>
  <mesh position={[0,-.95,1.2]}><boxGeometry args={[3.5,.16,1.7]}/><meshStandardMaterial color={c.base}/></mesh>{[-1,1].map(side=><mesh key={'wall'+side} position={[side*1.7,-.63,1.2]}><boxGeometry args={[.13,.62,1.7]}/><meshStandardMaterial color={c.lid}/></mesh>)}{[-1,1].map(side=><mesh key={'edge'+side} position={[0,-.63,1.2+side*.78]}><boxGeometry args={[3.5,.62,.13]}/><meshStandardMaterial color={c.base}/></mesh>)}<mesh position={[0,-.85,1.2]}><boxGeometry args={[3.24,.04,1.43]}/><meshStandardMaterial color="#f5dfcb"/></mesh>
  {shopSlots.map(slot=>{const item=box.shop.items.find(i=>i.slot===slot);return <group key={slot} position={[(slot-1)*1.04,-.53,1.2]} onClick={e=>{e.stopPropagation();if(selected)onPlace(slot);else if(item)onPick(item.kind);}}><mesh position={[0,-.28,0]}><cylinderGeometry args={[.45,.45,.025,24]}/><meshStandardMaterial color={selected?'#ba9f79':r}/></mesh>{item?<group scale={.38}><ShopItemModel kind={item.kind} box={box}/></group>:<mesh position={[0,-.15,0]}><boxGeometry args={[.65,.2,.6]}/><meshStandardMaterial color="#fcf3e5" transparent opacity={.6}/></mesh>}</group>;})}
 </>;
}
export default function GiftShopScene({box,selected,onPick,onPlace,onFailure}:{box:BoxConfig;selected:ShopKind|null;onPick:(kind:ShopKind)=>void;onPlace:(slot:ShopSlot)=>void;onFailure:()=>void}){return <Canvas frameloop="demand" dpr={[1,1.5]} camera={{position:[3.8,3.0,7.8],fov:39}} gl={{antialias:true,alpha:true,powerPreference:'low-power'}}><Guard onFailure={onFailure}/><ambientLight intensity={1.7}/><directionalLight position={[3,5,5]} intensity={2.6} color="#fff1dd"/><directionalLight position={[-4,3,1]} intensity={1.0} color="#f7c1c1"/><Room box={box} selected={selected} onPick={onPick} onPlace={onPlace}/><OrbitControls enablePan={false} enableZoom={false} minAzimuthAngle={-.35} maxAzimuthAngle={.6} minPolarAngle={.72} maxPolarAngle={1.18}/></Canvas>;}
