import {useEffect,useState} from 'react';
import QRCode from 'qrcode';
import {downloadBlob} from './common';
import type {Language} from '@/lib/i18n';
export function GiftCard({url,lang='en'}:{url:string;lang?:Language}){
 const [recipient,setRecipient]=useState(''),[sender,setSender]=useState(''),[message,setMessage]=useState('A little gift, made just for you.'),[qr,setQr]=useState(''),[error,setError]=useState(''),my=lang==='my';
 useEffect(()=>{let active=true;QRCode.toString(url,{type:'svg',width:320,margin:4,errorCorrectionLevel:'M'}).then(svg=>{if(active)setQr(svg);}).catch(()=>{if(active)setError('QR generation failed.');});return()=>{active=false;};},[url]);
 const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
 function download(){const html=`<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OurStory gift card</title><style>@page{size:A5;margin:12mm}*{box-sizing:border-box}body{font-family:Arial,'Myanmar Text',sans-serif;background:#fff8f0;color:#293d35;margin:0;padding:30px}.card{max-width:540px;margin:auto;border:1px solid #cba8b2;border-radius:24px;padding:35px;text-align:center}h1{font:36px Georgia,serif;color:#a44860}p{line-height:1.9;overflow-wrap:anywhere;white-space:pre-wrap}.qr{max-width:240px;margin:20px auto}.qr svg{width:100%;height:auto}.link{font-size:11px;word-break:break-all}.note{font-size:12px}@media print{body{padding:0;background:white}.card{break-inside:avoid}}</style></head><body><main class="card"><h1>OurStory ♡</h1><p>${my?'သို့':'To'} ${escape(recipient)}</p><p>${escape(message)}</p><div class="qr">${qr}</div><p>${my?'မေတ္တာဖြင့်':'With love'}, ${escape(sender)}</p><p class="note">${my?'လက်ဆောင်ဖွင့်ရန် QR ကို scan လုပ်ပါ။':'Scan to open your personal gift.'}</p><p class="link"><a href="${escape(url)}">${escape(url)}</a></p><p class="note">${my?'PIN ကို သီးခြားပေးပါ။ လက်ဆောင် link သည် သက်တမ်းအတွင်း online ရှိရပါမယ်။':'Share the PIN separately. The gift must be online and within its hosting period.'}</p></main></body></html>`;downloadBlob(new Blob([html],{type:'text/html;charset=utf-8'}),'ourstory-printable-gift-card.html');}
 return <details className="gift-card-builder"><summary>{my?'Printable QR လက်ဆောင်ကတ် ဖန်တီးမယ်':'Create a printable gift QR card'}</summary><label>{my?'လက်ခံသူ':'Recipient'}<input maxLength={60} value={recipient} onChange={e=>setRecipient(e.target.value)}/></label><label>{my?'ပေးပို့သူ':'Sender'}<input maxLength={60} value={sender} onChange={e=>setSender(e.target.value)}/></label><label>{my?'ကတ်ပေါ်က စာလေး':'Card message'}<textarea rows={3} maxLength={250} value={message} onChange={e=>setMessage(e.target.value)}/></label><div className="print-card-preview"><h3>OurStory ♡</h3><p>{recipient}</p><p>{message}</p><div dangerouslySetInnerHTML={{__html:qr}}/><p>{sender}</p></div><button type="button" className="btn outline" disabled={!qr} onClick={download}>{my?'ကတ် HTML ဒေါင်းမယ်':'Download printable card'}</button><small>{my?'ဒေါင်းထားတဲ့ HTML ကို browser မှာဖွင့်ပြီး Cmd+P → Print / Save as PDF လုပ်ပါ။':'Open the downloaded HTML in your browser, then Cmd+P → Print / Save as PDF.'}</small>{error&&<p role="alert">{error}</p>}</details>;
}
