import {useEffect,useId,useRef,useState} from 'react';
import {Music2,Play,Pause,Volume2} from 'lucide-react';
import {ambientTracks,readMusic,youtubeEmbedUrl,type MusicConfig} from '@/lib/music';
import type {Language} from '@/lib/i18n';
export function MusicPlayer({value,lang='en',compact=false}:{value?:MusicConfig;lang?:Language;compact?:boolean}){
 const music=readMusic(value),track=ambientTracks.find(t=>t.id===music.ambient)!,my=lang==='my',audio=useRef<HTMLAudioElement>(null),id=useId();
 const [playing,setPlaying]=useState(false),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[volume,setVolume]=useState(music.volume),[error,setError]=useState('');
 useEffect(()=>{setVolume(music.volume);},[music.volume]);
 useEffect(()=>{if(audio.current)audio.current.volume=volume/100;},[volume,music.source,music.ambient]);
 useEffect(()=>{setLoaded(false);setError('');setPlaying(false);audio.current?.pause();},[music.source,music.ambient,music.youtubeUrl,music.startSeconds]);
 useEffect(()=>{const ownedAudio=audio.current;const stop=()=>{audio.current?.pause();setLoaded(false);};const visibility=()=>{if(document.hidden)stop();};const otherAudio=(event:Event)=>{if(event.target!==audio.current)stop();};document.addEventListener('visibilitychange',visibility);document.addEventListener('play',otherAudio,true);return()=>{document.removeEventListener('visibilitychange',visibility);document.removeEventListener('play',otherAudio,true);ownedAudio?.pause();};},[music.source]);
 if(music.source==='none')return null;
 if(compact)return <div className="music-preview-badge"><Music2 size={15}/>{my?'လက်ခံသူက Play နှိပ်မှ တေးသံဖွင့်မယ်':'Music starts when they press Play'}</div>;
 const embed=youtubeEmbedUrl(music.youtubeUrl,music.loop,music.startSeconds);
 return <section className="gift-music" aria-labelledby={id} lang={lang}><div className="music-heading"><span className="music-icon" aria-hidden="true"><Music2 size={22}/></span><div><h2 id={id}>{my?'ဒီအမှတ်တရအတွက် တေးသံလေး':'A soundtrack for this moment'}</h2><p>{music.source==='ambient'?(my?track.my:track.name):(my?'ရွေးထားတဲ့ YouTube တေးသီချင်း':'A song chosen just for you')}</p></div></div>
 {music.source==='ambient'?<><audio ref={audio} src={track.file} preload="none" loop={music.loop} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onError={()=>setError(my?'တေးသံ ဖွင့်မရသေးပါ။ ပြန်စမ်းပါ။':'The soundtrack could not load. Try again.')}/><div className="music-controls"><button type="button" className="btn primary small" disabled={busy} aria-pressed={playing} onClick={async()=>{const player=audio.current;if(!player)return;setError('');if(!player.paused){player.pause();return;}setBusy(true);try{player.volume=volume/100;await player.play();}catch{setError(my?'Play ကို ပြန်နှိပ်ပါ။':'Press Play to try again.');}finally{setBusy(false);}}}>{playing?<Pause size={16}/>:<Play size={16}/>} {my?(playing?'ခဏရပ်မယ်':'တေးသံဖွင့်မယ်'):(playing?'Pause music':'Play music')}</button><label><Volume2 size={16}/><span>{my?'အသံအတိုးအကျယ်':'Volume'}</span><input aria-label={my?'တေးသံ အသံအတိုးအကျယ်':'Music volume'} type="range" min="0" max="100" value={volume} onChange={e=>setVolume(Number(e.target.value))}/><output>{volume}%</output></label></div><small>{my?'ကိုယ်တိုင် ဖန်တီးထားတဲ့ ambient တေးသွား · အလိုအလျောက် မဖွင့်ပါ':'Original ambient soundtrack · playback is always your choice'}</small></>:<><p className="music-privacy">{my?'Player ဖွင့်မှ YouTube နဲ့ ချိတ်ဆက်ပါမယ်။ Player ထဲက Play၊ Pause နဲ့ volume ကို သုံးပါ။':'Load the player to connect to YouTube, then use its Play, Pause and volume controls.'}</p>{loaded&&embed?<><iframe className="youtube-music-frame" src={embed} title={my?'ရွေးထားတဲ့ YouTube တေးသီချင်း':'Your chosen YouTube music video'} width="480" height="270" referrerPolicy="strict-origin-when-cross-origin" allow="encrypted-media; fullscreen; picture-in-picture" allowFullScreen/><button type="button" className="btn outline small" onClick={()=>setLoaded(false)}>{my?'တေးသံရပ်ပြီး Player ပိတ်မယ်':'Stop & close player'}</button></>:<button type="button" className="btn primary small" onClick={()=>setLoaded(true)}>{my?'YouTube Player ဖွင့်မယ်':'Load YouTube player'}</button>}<a className="music-external" href={music.youtubeUrl} target="_blank" rel="noopener noreferrer">{my?'ဒီမှာဖွင့်မရရင် YouTube မှာကြည့်ပါ':'If the video cannot play here, open it on YouTube'} ↗</a></>}
 {error&&<p role="alert" className="music-error">{error}</p>}
 </section>;
}
