import {useState} from 'react';
import {ambientTracks,musicSchema,readMusic,type MusicConfig} from '@/lib/music';
import type {Language} from '@/lib/i18n';
import {MusicPlayer} from './music-player';
export function MusicPicker({value,onChange,lang}:{value?:MusicConfig;onChange:(value:MusicConfig)=>void;lang:Language}){
 const music=readMusic(value),my=lang==='my',[link,setLink]=useState(music.youtubeUrl),[error,setError]=useState('');
 function applyLink(){const next=musicSchema.safeParse({...music,source:'youtube',youtubeUrl:link});if(!next.success){setError(my?'မှန်ကန်တဲ့ HTTPS YouTube video link ထည့်ပါ။':'Enter a valid HTTPS YouTube video link.');return;}onChange(next.data);setLink(next.data.youtubeUrl);setError('');}
 return <section className="music-picker"><h3>{my?'နောက်ခံ တေးသံလေး ထည့်မယ်':'Add a background soundtrack'}</h3><p>{my?'လက်ခံသူက ကိုယ်တိုင် Play နှိပ်ပြီး နားဆင်နိုင်မယ်။':'Let them choose when to listen while reading your gift.'}</p><div className="reveal-effect-options">{(['none','ambient','youtube'] as const).map(source=><button type="button" key={source} aria-pressed={music.source===source} onClick={()=>{setError('');if(source==='youtube'){if(link.trim())applyLink();else setError(my?'အောက်မှာ YouTube link ထည့်ပြီး Add နှိပ်ပါ။':'Paste a link below and press Add YouTube song.');}else onChange({...music,source});}}>{source==='none'?(my?'တေးသံ မပါ':'No music'):source==='ambient'?(my?'ပါဝင်တဲ့ တေးသွားများ':'Ambient sounds'):'YouTube'}</button>)}</div>
 {music.source==='ambient'&&<><label>{my?'တေးသွားရွေးပါ':'Choose an original soundtrack'}<select value={music.ambient} onChange={e=>onChange({...music,ambient:e.target.value as MusicConfig['ambient']})}>{ambientTracks.map(track=><option key={track.id} value={track.id}>{my?track.my:track.name}</option>)}</select></label><label>{my?'အစပြု အသံအတိုးအကျယ်':'Starting volume'}<input type="range" min="0" max="100" value={music.volume} onChange={e=>onChange({...music,volume:Number(e.target.value)})}/><small>{music.volume}%</small></label></>}
 <label>{my?'YouTube တေးသီချင်း link':'YouTube music link'}<input type="url" maxLength={500} value={link} placeholder="https://www.youtube.com/watch?v=…" onChange={e=>{setLink(e.target.value);setError('');}}/><small>{my?'Watch၊ youtu.be၊ Shorts၊ live နဲ့ music.youtube.com video links ရပါတယ်။':'Supports watch, youtu.be, Shorts, live and music.youtube.com video links.'}</small></label><div className="button-row"><button type="button" className="btn outline small" onClick={applyLink}>{my?'YouTube တေးသီချင်း ထည့်မယ်':'Add YouTube song'}</button>{music.youtubeUrl&&<button type="button" className="text-link" onClick={()=>{onChange({...music,source:music.source==='youtube'?'none':music.source,youtubeUrl:''});setLink('');setError('');}}>{my?'Link ဖယ်မယ်':'Remove link'}</button>}</div>
 {error&&<p role="alert" className="music-error">{error}</p>}
 {music.source==='youtube'&&<label>{my?'စတင်မည့် အချိန် (seconds)':'Start at (seconds)'}<input type="number" min="0" max="86400" step="1" value={music.startSeconds} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=0&&n<=86400)onChange({...music,startSeconds:n});}}/><small>{my?'90 ဆိုရင် 1:30 မှ စဖွင့်မယ်။':'90 starts at 1:30. YouTube may begin at the nearest keyframe.'}</small></label>}{music.source!=='none'&&<label className="notification-choice"><input type="checkbox" checked={music.loop} onChange={e=>onChange({...music,loop:e.target.checked})}/>{my?'တေးသီချင်းကို ထပ်ခါတလဲလဲ ဖွင့်မယ်':'Repeat the soundtrack'}</label>}
 <MusicPlayer key={music.source+music.ambient+music.youtubeUrl} value={music} lang={lang}/><small className="music-privacy">{my?'YouTube video တချို့မှာ embed မရနိုင်ပါ။ တေးသီချင်းအသုံးပြုခွင့်ကို စစ်ပါ။':'Some YouTube videos cannot be embedded. Choose music you have permission to use.'}</small>
 </section>;
}
