import {useCallback,useEffect,useState} from 'react';
import {Bell,Check,RefreshCw} from 'lucide-react';
import {request,ErrorBox} from './common';
import type {Language} from '@/lib/i18n';
type Item={giftId:string;giftTitle:string;openedAt:number;readAt:number|null;emailStatus:string};
type Inbox={unread:number;items:Item[]};
export function OpeningNotifications({lang='en'}:{lang?:Language}){
 const [inbox,setInbox]=useState<Inbox>({unread:0,items:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),my=lang==='my';
 const load=useCallback(async()=>{const data=await request<Inbox>('/api/openings');setInbox(data);setError('');},[]);
 useEffect(()=>{let active=true;const update=()=>{if(active&&document.visibilityState==='visible')load().catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});};update();const timer=setInterval(update,30000);document.addEventListener('visibilitychange',update);return()=>{active=false;clearInterval(timer);document.removeEventListener('visibilitychange',update);};},[load]);
 return <section className="opening-notifications" aria-labelledby="opening-notifications-title"><div className="opening-inbox-heading"><div><h2 id="opening-notifications-title"><Bell size={20}/>{my?'လက်ဆောင် ဖွင့်ကြည့်မှုများ':'Gift opening notifications'}<span className="opening-unread" aria-label={my?'မဖတ်ရသေးသော အသိပေးချက်':'Unread notifications'}>{inbox.unread}</span></h2><p>{my?'လက်ဆောင်တစ်ခုစီ၏ ပထမဆုံးဖွင့်ချိန်ကို ကြည့်နိုင်ပါတယ်။':'See the first opening of each gift.'}</p></div><button type="button" className="btn outline small" disabled={!!busy} onClick={async()=>{setBusy('refresh');try{await load();}catch(e){setError((e as Error).message);}finally{setBusy('');setLoading(false);}}}><RefreshCw size={14}/>{my?'ပြန်စစ်မယ်':'Refresh'}</button></div><ErrorBox error={error}/>{loading?<p>{my?'ဖတ်နေပါတယ်…':'Loading…'}</p>:!inbox.items.length?<p className="muted">{my?'ဖွင့်ကြည့်မှု မရှိသေးပါ။ လက်ဆောင်ဖွင့်သည့်အခါ ဒီမှာပေါ်လာမယ်။':'No openings yet. A notification appears when someone opens a shared gift.'}</p>:<details open={inbox.unread>0}><summary>{my?'အသိပေးချက်များ ကြည့်မယ်':'View notifications'} · {inbox.items.length}</summary><ul className="opening-inbox-list">{inbox.items.map(item=><li key={item.giftId} className={item.readAt?'is-read':'is-unread'}><div><strong>{item.giftTitle}</strong><p>{my?'သင့်လက်ဆောင်ကို ဖွင့်ကြည့်ခဲ့ပါတယ်။':'Your gift was opened.'}</p><time dateTime={new Date(item.openedAt).toISOString()}>{new Date(item.openedAt).toLocaleString(my?'my-MM':'en-GB',{timeZone:'Asia/Yangon'})} · {my?'မြန်မာအချိန်':'Myanmar time'}</time>{item.emailStatus==='review'&&<small>{my?'Email ပို့မှု အတည်မပြုနိုင်သေးပါ။':'Email delivery needs operator review.'}</small>}</div><div className="button-row"><a className="btn outline small" href={'/edit/'+item.giftId}>{my?'လက်ဆောင်ကြည့်မယ်':'View gift'}</a>{!item.readAt&&<button type="button" className="btn outline small" disabled={!!busy} onClick={async()=>{setBusy(item.giftId);try{await request('/api/openings/'+item.giftId,{method:'PATCH'});await load();}catch(e){setError((e as Error).message);}finally{setBusy('');}}}><Check size={14}/>{my?'ဖတ်ပြီး':'Mark read'}</button>}</div></li>)}</ul></details>}<small className="opening-inbox-note">{my?'ဒီမှတ်တမ်းက လက်ဆောင် link ကိုင်ထားသူက ဖွင့်ခဲ့ကြောင်းပဲ ပြသသည်။ ဘယ်သူဖြစ်ကြောင်း အတည်မပြုနိုင်ပါ။ Email ကို Account မှာ ရွေးချယ်နိုင်ပါတယ်။':'An opening means someone with access opened the gift; it does not verify who they are. Manage email notices in Account.'} <a href="/account">{my?'Account သို့':'Account settings'} ↗</a></small></section>;
}
