import {useEffect,useState} from 'react';
import {Mail,Check,Trash2} from 'lucide-react';
import {Header,Footer,request,ErrorBox,Loader,Modal} from './common';
import type {Language} from '@/lib/i18n';
type Reply={id:string;giftId:string;giftTitle:string;senderName:string;message:string;createdAt:number;readAt:number|null};
export function Replies({name,lang}:{name:string;lang:Language}){
 const [replies,setReplies]=useState<Reply[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[deleting,setDeleting]=useState<Reply|null>(null),my=lang==='my';
 async function load(){setReplies(await request('/api/replies'));}
 useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 async function act(reply:Reply,method:'PATCH'|'DELETE'){setBusy(reply.id);setError('');try{await request('/api/replies/'+reply.id,{method});setDeleting(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <><Header name={name} lang={lang}/><main className="replies-workspace section-wrap" lang={lang}><div className="eyebrow"><Mail size={17}/>{my?'ချစ်ရသူဆီက ပြန်စာများ':'YOUR PRIVATE REPLIES'}</div><h1>{my?'လက်ဆောင်လေးနောက်က ပြန်စာများ။':<>A little love, <em>sent back.</em></>}</h1><p>{my?'နာမည်ကို ပေးပို့သူက ဖြည့်ထားခြင်းဖြစ်ပြီး identity verification မလုပ်ထားပါ။':'Notes are private to your account. Sender names are self-reported.'}</p><span className="reply-unread-count">{replies.filter(reply=>!reply.readAt).length} {my?'မဖတ်ရသေး':'unread'}</span><ErrorBox error={error}/>{loading?<Loader/>:!replies.length?<div className="empty-gifts"><Mail size={40}/><h2>{my?'ပြန်စာ မရောက်သေးပါ။':'No notes yet.'}</h2><p>{my?'Editor step 4 မှ Recipient replies ကိုဖွင့်ပြီး gift share လုပ်ပါ။':'Enable recipient replies in editor step 4, then share your gift.'}</p><a className="btn outline" href="/dashboard">{my?'လက်ဆောင်များ ကြည့်မယ်':'My gifts'}</a></div>:<div className="reply-inbox">{replies.map(reply=><article className={'reply-card '+(!reply.readAt?'unread':'')} key={reply.id}><div className="reply-card-top"><div><span>{reply.giftTitle}</span><h2>{reply.senderName}</h2></div><time>{new Date(reply.createdAt).toLocaleString(my?'my-MM':'en-GB',{timeZone:'Asia/Yangon',dateStyle:'medium',timeStyle:'short'})}</time></div><p>{reply.message}</p><div className="button-row"><a className="text-link" href={'/edit/'+reply.giftId}>{my?'လက်ဆောင်ပြင်မယ်':'Open gift editor'} ↗</a>{!reply.readAt&&<button className="btn outline small" disabled={!!busy} onClick={()=>act(reply,'PATCH')}><Check size={15}/>{my?'ဖတ်ပြီး':'Mark read'}</button>}<button className="icon-btn" disabled={!!busy} aria-label={my?'ပြန်စာဖျက်မယ်':'Delete reply'} onClick={()=>setDeleting(reply)}><Trash2 size={17}/></button></div></article>)}</div>}</main><Footer lang={lang}/>{deleting&&<Modal lang={lang} title={my?'ပြန်စာလေး ဖျက်မလား။':'Delete this reply?'} onClose={()=>setDeleting(null)}><div className="dialog-body"><p>{my?'ဒီစာကို အပြီးဖျက်မည်။':'This permanently deletes the private note.'}</p><button className="btn primary" disabled={!!busy} onClick={()=>act(deleting,'DELETE')}>{my?'ဖျက်မယ်':'Delete reply'}</button></div></Modal>}</>;
}
