import {useEffect,useId,useRef,useState} from 'react';
import {ChevronLeft,ChevronRight,Heart,MailOpen,Sparkle} from 'lucide-react';
import type {GiftContent} from '@/lib/gifts';
import {prettyDate} from '@/lib/gifts';
import type {Language} from '@/lib/i18n';
export function LetterEnvelope({content,lang}:{content:GiftContent;lang:Language}){
  const [opened,setOpened]=useState(false);const id=useId();
  const my=lang==='my', romantic=!content.occasion||content.occasion==='anniversary'||content.occasion==='valentine';
  return <section className={'experience-letter'+(opened?' is-open':'')}><span className="gift-label">{my?'သင့်အတွက် နှလုံးသားထဲက စာလေး':romantic?'A LITTLE LOVE, SEALED WITH CARE':'A MESSAGE, SEALED WITH CARE'}</span><h2>{my?(romantic?'မင်းအတွက်၊ အမြဲတမ်း။':'မင်းအတွက် စာလေးတစ်စောင်။'):(romantic?'For you, always.':'A little note, just for you.')}</h2><div className="letter-envelope-art" aria-hidden="true"><div className="envelope-object"><div className="envelope-back"/><div className="envelope-paper"><span>{my?content.partnerName+'ရေ၊':'Dear '+content.partnerName+','}</span><Heart size={24} strokeWidth={1}/><small>{my?'ချစ်ခြင်းများစွာဖြင့်':'With love'},<br/>{content.yourName}</small></div><div className="envelope-front"/><div className="envelope-flap"/><span className="envelope-wax"><Heart size={17}/></span></div></div><button className="btn primary" aria-expanded={opened} aria-controls={id} onClick={()=>setOpened(!opened)}><MailOpen size={17}/>{opened?(my?'စာအိတ်ကို ပြန်ပိတ်မယ်':'Close my letter'):(my?'စာအိတ်ကို ဖွင့်မယ်':'Open my letter')}</button><div className="envelope-full-letter" id={id} hidden={!opened}><div className="letter-text">{content.letter}</div><Heart size={22} strokeWidth={1}/></div></section>;
}
export function MemoryAlbum({content,urls,lang,onPhoto,motionOff}:{content:GiftContent;urls:string[];lang:Language;onPhoto:(index:number)=>void;motionOff:boolean}){
  const [page,setPage]=useState(0),[turned,setTurned]=useState(false),[tilt,setTilt]=useState({x:0,y:0});const touch=useRef<number|null>(null),my=lang==='my';
  useEffect(()=>{setPage(p=>Math.min(p,Math.max(0,urls.length-1)));},[urls.length]);
  if(!urls.length)return null;
  const go=(direction:number)=>{setPage(p=>(p+direction+urls.length)%urls.length);setTurned(true);};
  const caption=content.timeline[page]?.title||(my?'အမှတ်တရ '+(page+1):'Memory '+(page+1));
  return <section className="experience-album"><span className="gift-label">{my?'အမှတ်တရ မှတ်တမ်းလေးများ':'LITTLE MEMORIES, PAGE BY PAGE'}</span><h2>{my?'အမှတ်တရလေးတွေကို သိမ်းထားမယ်။':'Some moments deserve a forever.'}</h2><div className="album-perspective" onPointerMove={e=>{if(motionOff||e.pointerType!=='mouse')return;const b=e.currentTarget.getBoundingClientRect();setTilt({x:(e.clientX-b.left)/b.width*8-4,y:(e.clientY-b.top)/b.height*6-3});}} onPointerLeave={()=>setTilt({x:0,y:0})} onTouchStart={e=>{touch.current=e.touches[0]?.clientX??null;}} onTouchEnd={e=>{if(touch.current===null)return;const end=e.changedTouches[0]?.clientX??touch.current,dx=end-touch.current;touch.current=null;if(Math.abs(dx)>45&&urls.length>1)go(dx<0?1:-1);}}><div className="memory-book" style={{transform:motionOff?'none':`rotateY(${-9+tilt.x}deg) rotateX(${5-tilt.y}deg) rotate(-2deg)`}}><div className="album-left"><span className="album-number">{String(page+1).padStart(2,'0')}</span><h3>{caption}</h3><small>{content.timeline[page]?.date||prettyDate(content.date,lang)}</small><span className="album-names">{content.yourName} + {content.partnerName}</span></div><div key={page} className={'album-right'+(turned&&!motionOff?' page-turn':'')}><button onClick={()=>onPhoto(page)} className="album-polaroid" aria-label={(my?'ပုံကို အကြီးကြည့်မယ်၊ ':'Open photo: ')+caption}><img src={urls[page]} alt={caption} loading="lazy"/><span>{caption}</span></button></div></div></div><div className="album-navigation">{urls.length>1&&<button className="btn outline small" onClick={()=>go(-1)} aria-label={my?'အရင်စာမျက်နှာ':'Previous page'}><ChevronLeft size={20}/></button>}<span aria-live="polite">{(page+1).toLocaleString(my?'my-MM':'en-US')} / {urls.length.toLocaleString(my?'my-MM':'en-US')}</span>{urls.length>1&&<button className="btn outline small" onClick={()=>go(1)} aria-label={my?'နောက်စာမျက်နှာ':'Next page'}><ChevronRight size={20}/></button>}</div></section>;
}
export function MemoryConstellation({content,lang}:{content:GiftContent;lang:Language}){
  const [selected,setSelected]=useState(0);const host=useRef<HTMLDivElement>(null);const [size,setSize]=useState({w:600,h:310});const my=lang==='my';
  const memories=content.timeline;
  useEffect(()=>{if(!host.current)return;const observer=new ResizeObserver(([entry])=>setSize({w:entry.contentRect.width,h:entry.contentRect.height}));observer.observe(host.current);return()=>observer.disconnect();},[]);
  useEffect(()=>setSelected(s=>Math.min(s,Math.max(0,memories.length-1))),[memories.length]);
  if(!memories.length)return null;
  const positions=[[.17,.29],[.54,.17],[.83,.45],[.58,.8],[.2,.73]];
  const active=memories[selected]||memories[0];
  return <section className="experience-stars"><span className="gift-label">{my?'အမှတ်တရတစ်ခု၊ ကြယ်လေးတစ်ပွင့်':'A SKY FULL OF US'}</span><h2>{my?'ကြယ်လေးတွေနဲ့ ရေးထားတဲ့ ဇာတ်လမ်း။':'Written in the stars.'}</h2><div className="constellation-sky" ref={host} role="group" aria-label={my?'ကြယ်ကိုနှိပ်ပြီး အမှတ်တရ ဖတ်မယ်':'Select a star to read a memory'}><div className="constellation-specks" aria-hidden="true"/>{memories.slice(1).map((_,i)=>{const a=positions[i],b=positions[i+1],dx=(b[0]-a[0])*size.w,dy=(b[1]-a[1])*size.h;return <span key={i} className="constellation-line" aria-hidden="true" style={{left:a[0]*size.w,top:a[1]*size.h,width:Math.hypot(dx,dy),transform:`rotate(${Math.atan2(dy,dx)}rad)`}}/>;})}{memories.map((memory,i)=><button key={i} className={'memory-star'+(i===selected?' selected':'')} style={{left:positions[i][0]*100+'%',top:positions[i][1]*100+'%'}} aria-label={memory.title} aria-pressed={i===selected} onClick={()=>setSelected(i)}><Sparkle size={23}/><span>{i+1}</span></button>)}<span className="constellation-names" aria-hidden="true"><Heart size={22}/></span></div><div className="constellation-memory" aria-live="polite"><small>{active.date}</small><h3>{active.title}</h3><p>{active.note}</p></div></section>;
}
