import {useEffect,useState} from 'react';
import {Modal,ErrorBox,request} from './common';
import type {Gift,GiftContent,TemplateId} from '@/lib/gifts';
import type {BoxConfig} from '@/lib/box';
import type {Language} from '@/lib/i18n';
type Version={revision:number;savedAt:number;content:GiftContent;template:TemplateId;box:BoxConfig};
export function VersionHistory({giftId,lang,beforeRestore,onRestore,onClose}:{giftId:string;lang:Language;beforeRestore:()=>Promise<Gift|null>;onRestore:(gift:Gift)=>void;onClose:()=>void}){
 const [versions,setVersions]=useState<Version[]>([]),[selected,setSelected]=useState<Version|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),my=lang==='my';
 useEffect(()=>{request<{versions:Version[]}>('/api/gifts/'+giftId+'/history').then(r=>setVersions(r.versions)).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[giftId]);
 return <Modal lang={lang} title={my?'အရင် Version များ':'Version history'} onClose={onClose} wide><div className="version-history"><p>{my?'နောက်ဆုံး version 20 ခု ထိန်းထားတယ်။ စာနဲ့ design ကို ပြန်ယူမယ်။ PIN၊ payment နဲ့ သက်တမ်းကို မပြောင်းပါ။':'Keep up to 20 previous versions. Restore writing and design; PIN, payments and hosting stay current.'}</p><ErrorBox error={error}/>{loading?<p>{my?'ဖတ်နေပါတယ်…':'Loading…'}</p>:!versions.length?<p>{my?'အရင် version မရှိသေးပါ။ စာပြင်ပြီး Save လုပ်တဲ့အခါ သိမ်းထားမယ်။':'No previous versions yet. Edit and save a completed draft to create history.'}</p>:<div className="history-list">{versions.map(v=><button type="button" key={v.revision} aria-pressed={selected?.revision===v.revision} onClick={()=>setSelected(v)}><strong>#{v.revision} · {v.content.title||v.content.partnerName}</strong><small>{new Date(v.savedAt).toLocaleString(my?'my-MM':'en-GB',{timeZone:'Asia/Yangon'})} · {v.template}</small></button>)}</div>}{selected&&<article className="history-preview"><h3>{selected.content.title}</h3><p>{selected.content.yourName} → {selected.content.partnerName} · {selected.content.date}</p><p className="history-letter">{selected.content.letter}</p><small>{my?'ဖျက်ပြီးသားပုံတွေကို ပြန်မယူနိုင်ပါ။ လက်ရှိ plan ရဲ့ ပုံအရေအတွက်ကို လိုက်နာမယ်။':'Deleted photos cannot be recovered. Current photo limits apply.'}</small><button type="button" className="btn primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const current=await beforeRestore();if(!current)throw new Error('Save your gift first.');const r=await request<{gift:Gift;removedPhotos:number}>('/api/gifts/'+giftId+'/history',{method:'POST',body:JSON.stringify({revision:current.revision,versionRevision:selected.revision})});onRestore(r.gift);if(r.removedPhotos)setError(my?`${r.removedPhotos} ပုံ မရှိတော့လို့ မပါဝင်ပါ။`:`Restored; ${r.removedPhotos} unavailable or over-limit photos were omitted.`);else onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{my?'ဒီ Version ကို ပြန်ယူမယ်':'Restore this version'}</button></article>}</div></Modal>;
}
