import {templateSchema} from '@/lib/gifts';
import {boxSchema} from '@/lib/box';
import {z} from 'zod';
import {api,origin,ownGift,db,json,dto,validatePhotos,hashPin,ApiError,bucket} from '@/lib/server';
export const dynamic='force-dynamic';
type C={params:Promise<{id:string}>};
export async function GET(_req:Request,c:C){return api(async()=>{const {row}=await ownGift((await c.params).id);return json(dto(row));});}
export async function PUT(req:Request,c:C){return api(async()=>{origin(req);const {row}=await ownGift((await c.params).id);const b=z.object({revision:z.number().int(),content:z.unknown(),template:templateSchema,plan:z.enum(['basic','premium']),box:boxSchema.optional(),revealAt:z.number().int().min(0).max(Date.now()+366*86400000).nullable().optional(),pin:z.string().regex(/^(\d{4,12})?$/,'PIN must contain 4–12 digits.').optional()}).parse(await req.json());if(b.plan!==row.plan){const active=await db().prepare("SELECT id FROM orders WHERE gift_id=? AND (status='pending' OR (status='approved' AND id=? AND ?>?))").bind(row.id,row.paid_order_id,row.expires_at||0,Date.now()).first();if(active)throw new ApiError(409,'Your package is locked while an order is pending or hosting is active.');}if(b.revealAt&&['published','test'].includes(row.status)&&row.expires_at&&b.revealAt>=row.expires_at)throw new ApiError(400,'Choose a reveal time before your hosting expires.');const content=await validatePhotos(b.content,row,b.plan);const pin=b.pin===undefined?row.pin_hash:b.pin?await hashPin(b.pin):null;const result=await db().prepare('UPDATE gifts SET content=?,template=?,plan=?,pin_hash=?,reveal_at=?,box_config=?,revision=revision+1,updated_at=? WHERE id=? AND owner_id=? AND revision=?').bind(JSON.stringify(content),b.template,b.plan,pin,b.revealAt===undefined?row.reveal_at:b.revealAt,b.box?JSON.stringify(b.box):row.box_config,Date.now(),row.id,row.owner_id,b.revision).run();if(!result.meta.changes)throw new ApiError(409,'This gift changed in another tab. Reload before saving.');const next=await db().prepare('SELECT * FROM gifts WHERE id=?').bind(row.id).first<typeof row>();return json(dto(next!));});}
export async function DELETE(req:Request,c:C){return api(async()=>{origin(req);const {row}=await ownGift((await c.params).id);const keys=await db().prepare('SELECT object_key FROM media WHERE gift_id=?').bind(row.id).all<{object_key:string}>();await db().batch([db().prepare('DELETE FROM viewer_sessions WHERE gift_id=?').bind(row.id),db().prepare('DELETE FROM media WHERE gift_id=?').bind(row.id),db().prepare('DELETE FROM recipient_replies WHERE gift_id=?').bind(row.id),db().prepare('DELETE FROM reminder_deliveries WHERE gift_id=?').bind(row.id),db().prepare('DELETE FROM gifts WHERE id=? AND owner_id=?').bind(row.id,row.owner_id)]);if(keys.results.length)await bucket().delete(keys.results.map(x=>x.object_key));return json({ok:true});});}

