import {z} from 'zod';
import {shopSchema} from './gift-shop.ts';
export const boxColors={rose:{name:'Rose',base:'#ce8587',lid:'#e8a3a1'},lavender:{name:'Lavender',base:'#a69abb',lid:'#c5b8d9'},forest:{name:'Forest',base:'#345a4b',lid:'#537c68'},midnight:{name:'Midnight',base:'#283546',lid:'#42536c'},ivory:{name:'Ivory',base:'#dfd1bc',lid:'#f0e5d3'}};
export const ribbonColors={champagne:{name:'Champagne',color:'#f5dbc0'},ivory:{name:'Ivory',color:'#fff7eb'},rose:{name:'Rose',color:'#b85b6b'}};
export const giftStyles=[
 {id:'box',name:'Wrapped with love',my:'အချစ်လက်ဆောင်ဘူး',description:'A ribbon-tied box with a lifting lid.',myDescription:'ဖဲကြိုးနဲ့ ချည်ထားတဲ့ ဘူးလေးကို ဖွင့်ကြည့်မယ်။'},
 {id:'bouquet',name:'Forever flowers',my:'အမှတ်တရ ပန်းစည်း',description:'A hand-tied bouquet that blooms for you.',myDescription:'ချစ်ရသူအတွက် ဖြည်းဖြည်းပွင့်လာတဲ့ ပန်းစည်း။'},
 {id:'bear',name:'A little bear hug',my:'Teddy လေးရဲ့ အချစ်',description:'A soft teddy with a heart and a happy wave.',myDescription:'နှလုံးသားလေးကိုင်ပြီး လက်ပြနှုတ်ဆက်တဲ့ teddy လေး။'},
 {id:'heart',name:'Heart of gold',my:'အချစ်နှလုံးသား',description:'A sculpted heart rising from its keepsake stand.',myDescription:'လက်ဆောင်စင်လေးပေါ်က မြင့်တက်လာတဲ့ နှလုံးသား။'}
] as const;
export const revealEffects=[{id:'hearts',name:'Floating hearts',my:'နှလုံးသားလေးများ'},{id:'petals',name:'Flower petals',my:'ပန်းပွင့်လေးများ'},{id:'sparkles',name:'Golden sparkles',my:'ရွှေရောင် အလင်းလေးများ'},{id:'none',name:'Quiet reveal',my:'အလှုပ်အရှား အလှဆင်မပါ'}] as const;
export const giftFinishes={matte:{name:'Soft matte',my:'နူးညံ့တဲ့ matte',roughness:.88,metalness:0},satin:{name:'Satin glow',my:'တောက်ပတဲ့ satin',roughness:.38,metalness:.18},pearl:{name:'Pearl shine',my:'ပုလဲရောင်အလင်း',roughness:.19,metalness:.38}};
export const giftFrames=[{id:'none',name:'Open space',my:'အလှဆင်ဘောင်မပါ'},{id:'arch',name:'Keepsake arch',my:'အမှတ်တရ မုခ်ဘောင်'},{id:'orbit',name:'Golden orbit',my:'ရွှေရောင်ကွင်း'}] as const;
export const giftStickers=[{id:'none',name:'No sticker',my:'Sticker မပါ'},{id:'heart',name:'Love heart',my:'နှလုံးသား'},{id:'star',name:'Little star',my:'ကြယ်လေး'},{id:'flower',name:'Daisy seal',my:'ပန်းပွင့်'}] as const;
export const boxSchema=z.object({shop:shopSchema.default({enabled:false,items:[]}),finish:z.enum(['matte','satin','pearl']).default('matte'),frame:z.enum(['none','arch','orbit']).default('none'),sticker:z.enum(['none','heart','star','flower']).default('none'),accessory:z.enum(['none','bow','crown','party-hat']).default('none'),flowerKind:z.enum(['daisy','rose','tulip']).default('daisy'),flowerCount:z.union([z.literal(3),z.literal(5),z.literal(7)]).default(5),allowReply:z.boolean().default(false),secret:z.object({title:z.string().trim().max(80),message:z.string().trim().max(1500)}).default({title:'',message:''}),style:z.enum(['box','bouquet','bear','heart']).default('box'),effect:z.enum(['hearts','petals','sparkles','none']).default('hearts'),color:z.enum(['rose','lavender','forest','midnight','ivory']),ribbon:z.enum(['champagne','ivory','rose']),initials:z.string().trim().max(12).refine(s=>!/[\u0000-\u001f\u007f<>]/.test(s),'Use up to 12 visible characters for the initials.')});
export type BoxConfig=z.infer<typeof boxSchema>;
export const defaultBox:BoxConfig={shop:{enabled:false,items:[]},finish:'matte',frame:'none',sticker:'none',accessory:'none',flowerKind:'daisy',flowerCount:5,allowReply:false,secret:{title:'',message:''},style:'box',effect:'hearts',color:'rose',ribbon:'champagne',initials:''};
export function readBox(value:string|null|undefined):BoxConfig{try{return boxSchema.parse(JSON.parse(value||'null'));}catch{return {...defaultBox};}}
export function coupleInitials(yourName:string,partnerName:string){const first=(name:string)=>{const s=name.trim();if(!s)return '';return new Intl.Segmenter('my',{granularity:'grapheme'}).segment(s)[Symbol.iterator]().next().value?.segment||'';};return [first(yourName),first(partnerName)].filter(Boolean).join(' & ').slice(0,12);}
