import {Hono} from 'hono';
import {withRequest,type Env} from '../lib/runtime';
import {scheduledJobs} from './jobs';
import * as r0 from '../app/api/account/language/route';
import * as r1 from '../app/api/account/route';
import * as r2 from '../app/api/admin/orders/[id]/route';
import * as r3 from '../app/api/admin/qr/route';
import * as r4 from '../app/api/admin/route';
import * as r5 from '../app/api/auth/[action]/route';
import * as r6 from '../app/api/backups/restore/route';
import * as r7 from '../app/api/gifts/[id]/backup/route';
import * as r8 from '../app/api/gifts/[id]/history/route';
import * as r9 from '../app/api/gifts/[id]/photos/route';
import * as r10 from '../app/api/gifts/[id]/publish/route';
import * as r11 from '../app/api/gifts/[id]/route';
import * as r12 from '../app/api/gifts/[id]/voice/route';
import * as r13 from '../app/api/gifts/route';
import * as r14 from '../app/api/health/route';
import * as r15 from '../app/api/media/[id]/route';
import * as r16 from '../app/api/openings/[id]/route';
import * as r17 from '../app/api/openings/route';
import * as r18 from '../app/api/order-status/route';
import * as r19 from '../app/api/orders/[id]/proof/route';
import * as r20 from '../app/api/orders/[id]/route';
import * as r21 from '../app/api/payment-qr/route';
import * as r22 from '../app/api/public/[token]/opened/route';
import * as r23 from '../app/api/public/[token]/reply/route';
import * as r24 from '../app/api/public/[token]/route';
import * as r25 from '../app/api/public/[token]/unlock/route';
import * as r26 from '../app/api/replies/[id]/route';
import * as r27 from '../app/api/replies/route';
import * as r28 from '../app/api/setup/route';
import * as r29 from '../app/api/workspace/route';
import * as r30 from '../app/api/auth/google/route';
const app=new Hono<{Bindings:Env}>();
app.on('GET','/api/auth/google',async c=>(r30.GET as Function)(c.req.raw));
app.on('PUT','/api/account/language',async c=>(r0.PUT as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('GET','/api/account',async c=>(r1.GET as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('PUT','/api/account',async c=>(r1.PUT as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('POST','/api/admin/orders/:id',async c=>(r2.POST as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('POST','/api/admin/qr',async c=>(r3.POST as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('GET','/api/admin',async c=>(r4.GET as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('PUT','/api/admin',async c=>(r4.PUT as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('POST','/api/auth/:action',async c=>(r5.POST as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('POST','/api/backups/restore',async c=>(r6.POST as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('GET','/api/gifts/:id/backup',async c=>(r7.GET as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('GET','/api/gifts/:id/history',async c=>(r8.GET as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('POST','/api/gifts/:id/history',async c=>(r8.POST as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('POST','/api/gifts/:id/photos',async c=>(r9.POST as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('GET','/api/gifts/:id/photos',async c=>(r9.GET as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('POST','/api/gifts/:id/publish',async c=>(r10.POST as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('GET','/api/gifts/:id',async c=>(r11.GET as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('PUT','/api/gifts/:id',async c=>(r11.PUT as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('DELETE','/api/gifts/:id',async c=>(r11.DELETE as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('POST','/api/gifts/:id/voice',async c=>(r12.POST as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('DELETE','/api/gifts/:id/voice',async c=>(r12.DELETE as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('GET','/api/gifts',async c=>(r13.GET as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('POST','/api/gifts',async c=>(r13.POST as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('GET','/api/health',async c=>(r14.GET as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('GET','/api/media/:id',async c=>(r15.GET as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('DELETE','/api/media/:id',async c=>(r15.DELETE as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('PATCH','/api/openings/:id',async c=>(r16.PATCH as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('GET','/api/openings',async c=>(r17.GET as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('GET','/api/order-status',async c=>(r18.GET as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('GET','/api/orders/:id/proof',async c=>(r19.GET as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('POST','/api/orders/:id',async c=>(r20.POST as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('GET','/api/payment-qr',async c=>(r21.GET as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('POST','/api/public/:token/opened',async c=>(r22.POST as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('POST','/api/public/:token/reply',async c=>(r23.POST as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('GET','/api/public/:token',async c=>(r24.GET as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('POST','/api/public/:token/unlock',async c=>(r25.POST as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('PATCH','/api/replies/:id',async c=>(r26.PATCH as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('DELETE','/api/replies/:id',async c=>(r26.DELETE as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('GET','/api/replies',async c=>(r27.GET as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('POST','/api/setup',async c=>(r28.POST as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.on('GET','/api/workspace',async c=>(r29.GET as Function)(c.req.raw,{params:Promise.resolve(c.req.param())}));
app.all('/api/account/language',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'PUT'}}));
app.all('/api/account',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'GET, PUT'}}));
app.all('/api/admin/orders/:id',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'POST'}}));
app.all('/api/admin/qr',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'POST'}}));
app.all('/api/admin',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'GET, PUT'}}));
app.all('/api/auth/:action',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'POST'}}));
app.all('/api/auth/google',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'GET'}}));
app.all('/api/backups/restore',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'POST'}}));
app.all('/api/gifts/:id/backup',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'GET'}}));
app.all('/api/gifts/:id/history',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'GET, POST'}}));
app.all('/api/gifts/:id/photos',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'POST, GET'}}));
app.all('/api/gifts/:id/publish',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'POST'}}));
app.all('/api/gifts/:id',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'GET, PUT, DELETE'}}));
app.all('/api/gifts/:id/voice',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'POST, DELETE'}}));
app.all('/api/gifts',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'GET, POST'}}));
app.all('/api/health',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'GET'}}));
app.all('/api/media/:id',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'GET, DELETE'}}));
app.all('/api/openings/:id',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'PATCH'}}));
app.all('/api/openings',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'GET'}}));
app.all('/api/order-status',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'GET'}}));
app.all('/api/orders/:id/proof',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'GET'}}));
app.all('/api/orders/:id',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'POST'}}));
app.all('/api/payment-qr',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'GET'}}));
app.all('/api/public/:token/opened',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'POST'}}));
app.all('/api/public/:token/reply',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'POST'}}));
app.all('/api/public/:token',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'GET'}}));
app.all('/api/public/:token/unlock',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'POST'}}));
app.all('/api/replies/:id',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'PATCH, DELETE'}}));
app.all('/api/replies',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'GET'}}));
app.all('/api/setup',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'POST'}}));
app.all('/api/workspace',()=>Response.json({error:'Method not allowed.'},{status:405,headers:{Allow:'GET'}}));
app.notFound(()=>Response.json({error:'API route not found.'},{status:404}));
app.onError(error=>{console.error('Worker request failed',error.message);return Response.json({error:'Request failed. Please try again.'},{status:500});});
export default {fetch:(request:Request,env:Env,ctx:ExecutionContext)=>withRequest(env,request,async()=>env.MAINTENANCE_MODE==='true'?Response.json({error:'Maintenance in progress. Please try again soon.'},{status:503,headers:{'Retry-After':'300'}}):app.fetch(request,env,ctx)),scheduled:(_event:ScheduledController,env:Env,ctx:ExecutionContext)=>ctx.waitUntil(scheduledJobs(env))};
